spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5433/staff_attendance
    username: "user"
    password: "password"
    driver-class-name: org.postgresql.Driver

  mail:
    host:  smtp.gmail.com
    port: 587
    username: "testfinalprojecthdsd@gmail.com"
    password: "mtok umlt ssyc izvt"
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

server:
  port: 8084

