services:
  postgresql:
    image: "postgres"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5433:5432
    volumes:
      - ./data:/var/lib/postgresql/data